# Generated by Django 2.2.17 on 2020-12-25 10:16

import bmf.models
import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bmf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMFJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='queueing', max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('ps_seqs', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/code/bmf_web/media/jobs'), upload_to=bmf.models.job_upload, validators=[bmf.models.file_size_validator])),
                ('bg_seqs', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/code/bmf_web/media/jobs'), upload_to=bmf.models.job_upload, validators=[bmf.models.file_size_validator])),
                ('core_size', models.PositiveSmallIntegerField(default=3)),
                ('max_iterations', models.PositiveSmallIntegerField(default=1000)),
                ('no_tries', models.PositiveSmallIntegerField(default=1)),
                ('input_type', models.CharField(choices=[('fasta', 'fasta'), ('fastq', 'fastq'), ('seq', 'seq')], default='fasta', max_length=20)),
            ],
        ),
    ]
