# Generated by Django 2.2.17 on 2020-12-28 20:10

import bmf.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmf', '0002_bmfjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmfjob',
            name='bg_seqs',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/jobs'), upload_to=bmf.models.job_upload, validators=[bmf.models.file_size_validator]),
        ),
        migrations.AlterField(
            model_name='bmfjob',
            name='ps_seqs',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/jobs'), upload_to=bmf.models.job_upload, validators=[bmf.models.file_size_validator]),
        ),
    ]
