# Generated by Django 2.2.17 on 2020-12-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmf', '0003_auto_20201228_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmfjob',
            name='is_bipartite',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
