# Generated by Django 2.2.17 on 2021-01-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmf', '0004_bmfjob_is_bipartite'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmfjob',
            name='is_example',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
